# Generated by Django 3.0.5 on 2020-05-14 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('filename', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
